### ISSUE TITLE
rescience-c.github.io gh pages deployment still active

### ISSUE THREAD

**Issue by pboesu** [ReScience/rescience.github.io#100]
A google search just took me to the still active github-pages deployment of the old ReScience C website (from this repo: https://github.com/rescience-c/rescience-c.github.io ). 
I appreciate the importance of keeping the old repo for archival purposes, but the active deployment is a bit misleading, as it looks identical to the current website but only lists publications up to 2018.

**Comment by rougier** [comment]
Oh thanks. I'm not sure how to deactivate it though.

**Comment by rougier** [comment]
I've found.
