### ISSUE TITLE
Submit the replication of my own research not allowed

### ISSUE THREAD

**Issue by fabiansinz** [ReScience/rescience.github.io#16]
**Comment has moved to https://github.com/ReScience/ReScience/issues/19**

<strike>I'd like to strongly suggest to rethink that restriction. I really like the idea of this journal, but I fear that this restriction will be a substantial limiting factor for the number of submissions and the usefulness of the journal. 

<strike>A very obvious reason for this is that time is limited for all of us. Therefore, we usually never reproduce the results of an entire paper, but only the parts that are relevant to us. Would you then accept code that reproduces parts of that paper?</strike>

<strike>More importantly, I don't think that this restriction really promotes reproducible research. By only allowing reproduced results from people other than the authors, you are basically checking whether the methods part of a paper is sufficient to reproduce the results. While that should be the case, it is unfortunately only true in rare situations. There are various reasons for this:
- Journals have word limitations.
- Condensing a complex analysis into a few paragraphs in a methods part is a daunting task and it is very easy to fail. 
- The data has not been published. </strike>

<strike>The best reproduction of an analysis is its code. This is why code should always be published with a paper. Unfortunately, this is not common practice and even if the code is published, I haven't seen a single instance in which it was reviewed. I thought that ReScience could fill this gap perfectly and who would be better suited to supply it than then authors?</strike>

<strike>Let's say you allowed authors to publish their analysis. This would mean that they would have to provide the data (because you need to be able to run it) and you would have at least one running instance that reproduces the results. It might have mistakes and biases, but at least it is one entire running instance. Others who are insterested in reproducing the paper could look at the code and, with the methods part of the paper, figure out what the authors did. If they find a error or a particular bias in the analysis, they could still submit an issue to the code repository. The time required to understand and reproduce the results, however, would be drastically reduced. I feel this would serve reproducibility much more than the hope that people spend significant time to reproduce an entire paper. </strike>

**Comment by rougier** [comment]
Hello Fabian,

I will try to answer your questions but could you first move (copy) your issue to https://github.com/ReScience/ReScience/issues which is the main place for questions ?

**Comment by fabiansinz** [comment]
Ok. I'll move it over.

**Comment by rougier** [comment]
Thanks.
