### ISSUE TITLE
Review of the edit webpage

### ISSUE THREAD

**Issue by rougier** [ReScience/rescience.github.io#33]
We've applied for membership to the [Open Access Scholarly Publishers Association](http://oaspa.org) and we've been asked to review the [edit](https://github.com/ReScience/rescience.github.io/blob/master/03-edit.md) page because it could be improved (English / grammatical errors most probably). Any volunteers?

**Comment by bruAristimunha** [comment]
I don't know if it's the right place, but I think I found a little mistake on the page.

In the page: https://rescience.github.io/read/

"Compuational", "Computatioal",  instead of "Computational"

**Comment by khinsen** [comment]
Thanks @bruAristimunha for reporting this. The two typos are fixed in the bibliography, so they will be fixed on the Web page the next time it is rebuilt.

**Comment by bruAristimunha** [comment]
English is not my first language, so there may be some false positives, but I looked at the other pages:

https://rescience.github.io/edit/
ommission -> omission 
possiblity -> possibility
----
https://rescience.github.io/faq/
concensus -> consensus
ben -> been
---
https://rescience.github.io/news/
Sience -> Science
publised -> published

**Comment by rougier** [comment]
@bruAristimunha Thanks. Can you make a PR ? (you can do it directly from within GitHub)

**Comment by bruAristimunha** [comment]
> @bruAristimunha Thanks. Can you make a PR ? (you can do it directly from within GitHub)

Done :)

**Comment by rougier** [comment]
Thanks !
