### ISSUE TITLE
Where can I suggest a replication?

### ISSUE THREAD

**Issue by alex-konovalov** [ReScience/rescience.github.io#62]
http://rescience.github.io/faq/ includes this

Can I suggest a replication?

Yes. If you want to suggest an article for a replication, just open a new issue in the call for replication repository and give the reference of the original article and possibly the reason you would like to see this article replicated (please refrain from suggesting your own work). Note that you’re also encouraged to register as a reviewer such that you can review the replication you’ve been proposing if someone actually takes up the challenge.

If you’re looking for some challenge, you can also look at the current list of suggestions. 

But all links are broken. Should they point to https://github.com/ReScience/call-for-replication ?

**Comment by rougier** [comment]
Oh yes, you're right, thanks. Can you make a PR for that change ?

**Comment by alex-konovalov** [comment]
@rougier done - please see https://github.com/ReScience/rescience.github.io/pull/63
