### ISSUE TITLE
Instructions for becoming a reviewer

### ISSUE THREAD

**Issue by TrashBirdEcology** [ReScience/rescience.github.io#69]
It's not clear how one requests to be put on the reviewer list. 

On the [FAQ webpage](http://rescience.github.io/faq/), there is the instruction to: "Become a reviewer by filling your information", which links to the [editorial board and reviewers list](https://github.com/rescience/rescience.github.io/blob/sources/04-board.md).

I assume I am to submit a PR containing my information in the reviewers list -- could you make this instruction more explicit somewhere? If this is the method, to which branch should I request the PR? Master?

**Comment by oliviaguest** [comment]
Yup! See this as an example: https://github.com/ReScience/rescience.github.io/pull/66

**Comment by oliviaguest** [comment]
> I assume I am to submit a PR containing my information in the reviewers list -- could you make this instruction more explicit somewhere? If this is the method, to which branch should I request the PR? Master?

Branch: sources. If I understand correctly! But I am tagging @rougier @khinsen and @benoit-girard just to make 100% sure.

**Comment by oliviaguest** [comment]
Oh, now, I see there is also this too: https://github.com/ReScience/ReScience/issues/27

**Comment by TrashBirdEcology** [comment]
Okay, thanks. I still recommend making this explicit somewhere in the repo

**Comment by oliviaguest** [comment]
Me too!

**Comment by khinsen** [comment]
Adding a comment to https://github.com/ReScience/ReScience/issues/27 is the easiest way, but a PR against the default branch (`sources`) is fine as well. See https://github.com/ReScience/rescience.github.io/pull/68 for an example.

**Comment by TrashBirdEcology** [comment]
Yeah, thanks I just added to the issue. I am not going to close this because the request was to make it more obvious as to how to do this. 

But please feel free to close this issue if you need.

**Comment by khinsen** [comment]
Done. Thanks @TrashBirdEcology for raising this issue!
