### ISSUE TITLE
Glossary for Re, Rp, etc?

### ISSUE THREAD

**Issue by oliviaguest** [ReScience/rescience.github.io#77]
I noticed we use "Re" to mean full replication and "Rp" to mean partial (in the titles) — is this right? Do we have a place where these are explained and clarified for us/our readers?

**Comment by khinsen** [comment]
"Re" for replication has been around since the beginnings. "Rp" for reproduction was introduced for the ten-year challenge. Either one can be negated ("¬Re", "¬Rp") in case of failure. There is nothing for partial success, as far as I know.

**Comment by oliviaguest** [comment]
Would be cool/useful to list these on the website, I think?

**Comment by rougier** [comment]
Yes, we can explain this in the FAQ or in the "write" section of the site.

**Comment by oliviaguest** [comment]
Perfect. What are the currently used options just the four mentioned/implied above?

**Comment by rougier** [comment]
Yes, until now we have only those options and the "¬Rp" has never been used.

**Comment by khinsen** [comment]
Minor correction: we have one "¬Rp"  submission (my own), but no "¬Re"  yet as far as I can see.

**Comment by oliviaguest** [comment]
OK, what do you think of: https://github.com/ReScience/rescience.github.io/commit/880a77f1236fe0d431ff57c5090912699d53609d?

**Comment by rougier** [comment]
Looks good to me. Maybe: "¬Re and ¬Rp." -> "¬Re (failed replication) and ¬Rp (failed repoduction)." Also, maybe we could add a reference to @labarba termionology article (https://arxiv.org/abs/1802.03311)

**Comment by oliviaguest** [comment]
Oh, yeah! Good idea. Add those when you compile the site? I actually haven't seen the docs on how to do that. Where are they?

**Comment by rougier** [comment]
There's a make script in the website but you can easily destroy eveything (as I did  once already) if you're not careful, meaning, if you don't have all the necessary plugin and the right ruby version. It's based on Jekyll but because we use the bibtex plugin, we have to build the site from the "sources" branch and push the result to master.

**Comment by rougier** [comment]
Best option so far is to ask me to rebuild it when necessary.

**Comment by oliviaguest** [comment]
Ah, OK. When you can then — thank you!

**Comment by rougier** [comment]
Done !

**Comment by oliviaguest** [comment]
Is this all good now? Or did I miss something out? We can probably close this issue? 😊
